-- AULA 14 -- ATUALIZAÇÃO E ELIMINAÇÃO DE DADOS

-- ELIMINAÇÃO DE DADOS ON DELETE CASCADE

-- CRIACAO DE SCHEMA
CREATE SCHEMA class_tables;

-- CRIACAO DE TABELAS
CREATE TABLE PAIS (
	pais_id INT PRIMARY KEY,
	nome_pais  VARCHAR(50)
);
	CREATE TABLE PESSOA (
	pessoa_id INT PRIMARY KEY,
	nome_completo  VARCHAR(60)
);

-- CRIAR FK
ALTER TABLE PESSOA 
ADD COLUMN pais_id INT,
ADD CONSTRAINT FK_PESSOAS_PAIS 
FOREIGN KEY (pais_id) REFERENCES PAIS(pais_id) ON DELETE CASCADE;

-- INSERT DE DADOS
INSERT INTO PAIS (pais_id, nome_pais) VALUES
	(1, 'Espanha'),
    (2, 'Italia'),
    (3, 'Argentina'),
    (4, 'Albania'),
    (5, 'Brasil');

INSERT INTO PESSOA (pessoa_id, nome_completo, pais_id) VALUES
	(1, 'Fernando Omar', 3),
    (2, 'Julian Conte', 3),
    (3, 'Nicolas Mariano', 1),
    (4, 'Laura Grisel', 2),
    (5, 'Constantino Pascual', 4);

-- DELETE
DELETE FROM pais WHERE pais_id = 3;
-- DELETE EXECUTADO DEVIDO RESTRIÇÃO ON CASCADE

-- DROP FK
ALTER TABLE PESSOA 
DROP FOREIGN KEY `FK_PESSOAS_PAIS`;

-- ADICIONAR FK ON DELETE RESTRICT
ALTER TABLE PESSOA 
ADD CONSTRAINT FK_PESSOAS_PAIS 
FOREIGN KEY (pais_id) REFERENCES PAIS(pais_id) ON DELETE RESTRICT;

-- DELETAR PAIS Q TEM RELACIONAMENTO FK
DELETE FROM PAIS WHERE pais_id = 1;

-- DELETAR PAIS SEM RELACIONAMENTO
DELETE FROM PAIS WHERE pais_id = 5;

-- DROP FK
ALTER TABLE PESSOA 
DROP FOREIGN KEY `FK_PESSOAS_PAIS`;

-- ADICIONAR FK ON DELETE SET NULL
ALTER TABLE PESSOA 
ADD CONSTRAINT FK_PESSOAS_PAIS 
FOREIGN KEY (pais_id) REFERENCES PAIS(pais_id) ON DELETE SET NULL;

-- DELETAR PAIS
DELETE FROM PAIS WHERE pais_id = 1; 

-- VALIDACAO
SELECT * FROM PESSOA;